name: Deploy Next.js to VM

on:
  push:
    branches: [ main ] # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust based on your Node.js version preference
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        
      - name: List built files
        run: |
          ls -la .next/
          ls -la public/
          ls -la

      # Create .env file if needed (use GitHub secrets for sensitive info)
      - name: Create production env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.production
          # Add other environment variables as needed

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          # Verify the keys were added
          cat ~/.ssh/known_hosts

      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Build Next.js app
        run: |
          npm run build
          ls -la .next/  # Verify build output exists
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r .next public package.json package-lock.json .env.production next.config.js deploy/
          tar -czvf deploy.tar.gz -C deploy .
      
      - name: Deploy to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2226
          source: "deploy.tar.gz"
          target: "${{ secrets.VM_DEPLOY_PATH }}"
          overwrite: true
      
      - name: Extract and restart on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2226
          script: |
            cd "${{ secrets.VM_DEPLOY_PATH }}"
            tar -xzvf deploy.tar.gz
            npm ci --production
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start

      # Run post-deployment commands on VM
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2226 # Your custom SSH port
          script: |
            cd ${{ secrets.VM_DEPLOY_PATH }}
            npm ci --production
            pm2 stop nextjs-app || true
            pm2 start npm --name "nextjs-app" -- start
            # Or if using systemd service:
            # sudo systemctl restart nextjs-app.service
